package dev.mark.llm.dto;

import java.util.List;

/**
* Data transfer object representing a standardized response from an LLM provider.
*
* - **Utility:** Encapsulates the generated text content, provider metadata, placeholder status, and requested tool calls in an immutable structure.
* - **Application Flow:** Acts as the standard output payload returned by LLM service integrations to be consumed by upstream business logic and controllers.
* - **Components:**
  - content: The text generated by the LLM.
  - provider: The name of the AI service that generated the response.
  - placeholder: Flag indicating if the response is a temporary placeholder.
  - toolCalls: List of tool or function execution requests returned by the LLM.
* - **Logic Integration:** Uses a compact constructor to ensure the toolCalls list is immutable and never null, safely integrating into the service pipeline where responses are processed, evaluated, or forwarded to clients.
*/

/**
* Standardized Data Transfer Object for Large Language Model provider responses.
*
* - **What it does:** Encapsulates generated text, provider metadata, placeholder flags, and tool calls in an immutable structure.
* - **Why it is useful:** Provides a unified response format across different LLM providers, ensuring safe and consistent data handling.
* - **Application flow:** Acts as the primary output payload returned by LLM service integrations for upstream controllers and business logic.
* - **Methods and variables:**
  - content: Holds the generated text response.
  - provider: Identifies the AI service used.
  - placeholder: Indicates a temporary response state.
  - toolCalls: Contains a list of requested function executions.
  - Compact constructor: Guarantees that the toolCalls list is never null and is fully immutable.
* - **Logic integration:** Fits into the service pipeline by normalizing provider outputs, allowing downstream components to process, evaluate, or forward responses safely without null-pointer risks.
*/

/**
* Standardized Data Transfer Object for Large Language Model provider responses.
*
* - **Purpose:** Encapsulates generated text, metadata, placeholder flags, and tool calls in an immutable structure.
* - **Application Flow:** Acts as the primary output payload returned by LLM service integrations for upstream controllers and business logic.
* - **Components:**
  - content: The generated text response.
  - provider: The name of the AI service.
  - placeholder: Indicates a temporary response state.
  - toolCalls: List of requested function executions.
* - **Logic Integration:** Uses a compact constructor to guarantee that the toolCalls list is never null and immutable, ensuring safe downstream processing in the service pipeline.
*/

/**
* Data transfer object representing a standardized response from an LLM provider.
*
* - **Utility:** Encapsulates the generated text content, provider metadata, placeholder status, and requested tool calls in an immutable structure.
* - **Application Flow:** Acts as the standard output payload returned by LLM service integrations to be consumed by upstream business logic and controllers.
* - **Components:**
  - content: The text generated by the LLM.
  - provider: The name of the AI service that generated the response.
  - placeholder: Flag indicating if the response is a temporary placeholder.
  - toolCalls: List of tool or function execution requests returned by the LLM.
- **Logic Integration:** Uses a compact constructor to ensure the toolCalls list is immutable and never null, safely integrating into the service pipeline where responses are processed, evaluated, or forwarded to clients.
*/

public record LlmResponseDTO(String content, String provider, boolean placeholder, List<LlmToolCallDTO> toolCalls) {
    public LlmResponseDTO {
        toolCalls = toolCalls == null ? List.of() : List.copyOf(toolCalls);
    }

    public LlmResponseDTO(String content, String provider, boolean placeholder) {
        this(content, provider, placeholder, List.of());
    }
}
