package dev.mark.llm.dto;

import java.util.Map;

/**
 * - **What the class does**: Represents the execution result (observation) of a specific tool call by the agent.
 * - **Why it is useful**: Encapsulates the outcome of an action, whether successful or failed, into a standardized format.
 * - **Application flow**: Returned by the Tool Executor back to the LLM context so the agent can reason about the result of its previous action.
 * - **Methods and variables**:
 *   - `toolCallId`: Matches the unique ID generated by the LLM for the request.
 *   - `toolName`: Identifies which tool was executed.
 *   - `successful`: Boolean flag indicating execution success.
 *   - `observation`: The raw text output or error message from the tool.
 *   - `metadata`: A non-null, immutable map for passing additional structured context (e.g. state changes).
 * - **Logic and fit**: Acts as the essential feedback loop mechanism, allowing the agent to continuously perceive the environment's response to its commands.
 */
public record LlmToolObservationDTO(
        String toolCallId,
        String toolName,
        boolean successful,
        String observation,
        Map<String, Object> metadata
) {
    public LlmToolObservationDTO {
        if (metadata == null) {
            metadata = Map.of();
        } else {
            metadata = Map.copyOf(metadata);
        }
    }

    public Map<String, Object> asMap() {
        return Map.of(
                "toolCallId", toolCallId,
                "toolName", toolName,
                "successful", successful,
                "observation", observation,
                "metadata", metadata
        );
    }
}
