package dev.mark.llm.dto;

import java.util.List;

/**
 * - Represents a structured list of execution steps generated by an LLM.
 * - Standardizes plan data transport and prevents exposure of internal domain models.
 * - Captures output from LLM planning services to be transmitted to controllers or clients.
 * - Contains a list of strings representing the sequential actions of the generated plan.
 * - Serves as an immutable container that decouples the LLM generation logic from subsequent execution logic.
 */
public record PlanResponseDTO(
        List<String> steps
) {
}
