package dev.mark.task.dto;

import dev.mark.agent.model.AgentStatusModel;
import dev.mark.agent.model.AgentStepModel;
import java.util.List;
import java.util.UUID;

/**
 * - Represents a Data Transfer Object returning task execution details to clients.
 * - Encapsulates the complete state, execution plan, individual steps, and final result of an asynchronous task into a single snapshot.
 * - Serves as the standard API output payload generated by service components and delivered by task controllers.
 * - Contains taskId, goal, status, finalAnswer, plan, and steps to provide full transparency into task progress and agent reasoning.
 * - Converts internal execution models (e.g., AgentStepModel, AgentStatusModel) into an immutable, client-friendly format for web or API consumption.
 */
public record TaskResponseDTO(
        UUID taskId,
        String goal,
        AgentStatusModel status,
        String finalAnswer,
        String currentAction,
        List<String> plan,
        List<AgentStepModel> steps
) {
}
